# Supabase Configuration for Commodity Options Training Game
# EU Region Configuration

[project]
# EU Region (Frankfurt)
# Replace with your actual project ID
project_id = "your-project-id"

[api]
enabled = true
# Port for local development
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# Port for local database
port = 54322
major_version = 15
# Shadow database for migrations
shadow_port = 54320
pool_size = 20
max_connections = 100

[db.pooler]
enabled = true
port = 54329
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
# Realtime configuration for game updates
ip_version = "IPv4"
max_events_per_second = 100

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true
# For CSV exports and game data
file_size_limit = "50MiB"
s3_protocol = "https"
s3_port = 443

[auth]
enabled = true
# EU-compliant auth settings
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = false
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.external.azure]
enabled = true
client_id = "env(AZURE_CLIENT_ID)"
secret = "env(AZURE_CLIENT_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"
# Microsoft Azure AD settings
url = "https://login.microsoftonline.com/common"

[functions]
# Edge Functions configuration
enabled = true
verify_jwt = true

# Educational compliance settings
[analytics]
enabled = false

[experimental]
s3_retries = 3
s3_timeout = 10
webhooks_retries = 3
webhooks_timeout_sec = 30

[logs]
# EU data retention compliance
retention_days = 30
