name: Verify Commodity Options Game Spec
on:
  push:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run verifier
        run: |
          node --version
          node scripts/verify-spec.mjs
